#!/usr/bin/env python3
"""Generate Spicetify theme from DMS auto-generated colors.

Reads ~/.cache/DankMaterialShell/dms-colors.json and produces a Spicetify color.ini.

Spicetify themes live in ~/.config/spicetify/Themes/<name>/color.ini.
After generating, activate with:
  spicetify config current_theme <name>
  spicetify apply

Usage:
  python3 generate_spicetify_theme.py                              # install dark + prompt apply
  python3 generate_spicetify_theme.py --name "dms-jade"            # custom theme name
  python3 generate_spicetify_theme.py --stdout                     # print to stdout only
  python3 generate_spicetify_theme.py --skip-apply                 # install only, no apply
"""

import argparse
import json
import os
import subprocess
import sys

DMS_COLORS_PATH = os.path.expanduser("~/.cache/DankMaterialShell/dms-colors.json")
SPICETIFY_THEMES_DIR = os.path.expanduser("~/.config/spicetify/Themes")

COLOR_INI_TPL = """\
; Auto-generated by dms-utils from {source}
; https://github.com/hthienloc/dms-utils

[{section}]
text               = {text}
subtext            = {subtext}
main               = {main}
sidebar            = {sidebar}
player             = {player}
card               = {card}
shadow             = {shadow}
selected-row       = {selected_row}
button             = {button}
button-active      = {button_active}
button-disabled    = {button_disabled}
tab-active         = {tab_active}
notification       = {notification}
notification-error = {notification_error}
misc               = {misc}
"""


def read_dms_colors(path):
    with open(path) as f:
        return json.load(f)


def strip_hash(h):
    return h.lstrip("#")


def extract_colors(dms_data, mode="dark"):
    c = dms_data.get("colors", {}).get(mode, {})
    surface = c.get("surface", "#1a1c1e")
    surface_container = c.get("surface_container", "#1e2023")
    surface_container_high = c.get("surface_container_high", "#292b2f")
    surface_container_highest = c.get("surface_container_highest", "#343740")
    on_surface = c.get("on_surface", "#e3e8ef")
    on_surface_variant = c.get("on_surface_variant", "#c4c7c5")
    primary = c.get("primary", "#42a5f5")
    on_primary = c.get("on_primary", "#ffffff")
    error = c.get("error", "#F2B8B5")
    error_container = c.get("error_container", "#8C1D18")
    outline_variant = c.get("outline_variant", c.get("surface_variant", "#44464f"))
    secondary = c.get("secondary", "#8ab4f8")

    return {
        "section": f"dms-{mode}",
        "text": strip_hash(on_surface),
        "subtext": strip_hash(on_surface_variant),
        "main": strip_hash(surface),
        "sidebar": strip_hash(surface_container),
        "player": strip_hash(surface_container),
        "card": strip_hash(surface_container_high),
        "shadow": strip_hash(c.get("shadow", "#000000")),
        "selected_row": strip_hash(on_surface_variant),
        "button": strip_hash(primary),
        "button_active": strip_hash(primary),
        "button_disabled": strip_hash(outline_variant),
        "tab_active": strip_hash(primary),
        "notification": strip_hash(surface_container_highest),
        "notification_error": strip_hash(error_container),
        "misc": strip_hash(secondary),
    }


def generate_ini(colors, source_name="dms-colors.json"):
    return COLOR_INI_TPL.format(source=source_name, **colors)


def install_theme(theme_dir, content):
    os.makedirs(theme_dir, exist_ok=True)
    path = os.path.join(theme_dir, "color.ini")
    with open(path, "w") as f:
        f.write(content)
    print(f"Written: {path}")
    return path


def spicetify_apply():
    try:
        subprocess.run(["spicetify", "apply"], check=True)
        print("spicetify apply: OK")
        return True
    except subprocess.CalledProcessError as e:
        print(f"spicetify apply failed: {e}", file=sys.stderr)
        return False
    except FileNotFoundError:
        print("spicetify not found on PATH.", file=sys.stderr)
        return False


def main():
    parser = argparse.ArgumentParser(description="Generate Spicetify theme from DMS colors")
    parser.add_argument("-n", "--name", default="dms",
                        help="Theme directory name (default: dms)")
    parser.add_argument("--stdout", action="store_true", help="Print color.ini to stdout")
    parser.add_argument("--skip-apply", action="store_true",
                        help="Install but don't run spicetify apply")
    args = parser.parse_args()

    if not os.path.exists(DMS_COLORS_PATH):
        print(f"Error: {DMS_COLORS_PATH} not found.", file=sys.stderr)
        sys.exit(1)

    dms_data = read_dms_colors(DMS_COLORS_PATH)
    colors_dark = extract_colors(dms_data, "dark")
    colors_light = extract_colors(dms_data, "light")

    ini = generate_ini(colors_dark) + "\n" + generate_ini(colors_light)

    if args.stdout:
        print(ini, end="")
        return

    theme_dir = os.path.join(SPICETIFY_THEMES_DIR, args.name)
    install_theme(theme_dir, ini)

    theme_name = args.name

    def set_and_apply():
        try:
            subprocess.run(["spicetify", "config", "current_theme", theme_name], check=True)
            print(f"spicetify config current_theme {theme_name}: OK")
        except subprocess.CalledProcessError as e:
            print(f"spicetify config failed: {e}", file=sys.stderr)
            return
        spicetify_apply()

    print(f"\nActivate:\n  spicetify config current_theme {theme_name}\n  spicetify apply")

    if not args.skip_apply:
        resp = input("\nRun spicetify config + apply now? (y/N): ").lower()
        if resp == "y":
            set_and_apply()


if __name__ == "__main__":
    main()
