#!/usr/bin/env python3
"""Generate Vesktop/Vencord theme from DMS auto-generated colors.

Reads ~/.cache/DankMaterialShell/dms-colors.json and produces a CSS theme file.

Usage:
  python3 generate_vesktop_theme.py                                          # dark mode, flatpak path
  python3 generate_vesktop_theme.py --mode light                             # light mode
  python3 generate_vesktop_theme.py -o ~/.config/vesktop/themes/my.css       # custom output
  python3 generate_vesktop_theme.py --stdout                                 # print to stdout
"""

import argparse
import json
import os
import sys

DMS_COLORS_PATH = os.path.expanduser("~/.cache/DankMaterialShell/dms-colors.json")
FLATPAK_PATH = os.path.expanduser("~/.var/app/dev.vencord.Vesktop/config/vesktop/themes/dank-discord.css")
NATIVE_PATH = os.path.expanduser("~/.config/vesktop/themes/dank-discord.css")
VENOCRD_PATH = os.path.expanduser("~/.config/Vencord/themes/dank-discord.css")


def read_dms_colors(path):
    with open(path) as f:
        return json.load(f)


def extract_colors(dms_data, mode="dark"):
    colors = dms_data.get("colors", {}).get(mode, {})
    return {
        "surface": colors.get("surface", "#1a1c1e"),
        "surface_container_low": colors.get("surface_container_low", "#181a1d"),
        "surface_container": colors.get("surface_container", "#1e2023"),
        "surface_container_high": colors.get("surface_container_high", "#292b2f"),
        "surface_container_highest": colors.get("surface_container_highest", "#343740"),
        "on_surface": colors.get("on_surface", "#e3e8ef"),
        "on_surface_variant": colors.get("on_surface_variant", "#c4c7c5"),
        "primary": colors.get("primary", "#42a5f5"),
        "on_primary": colors.get("on_primary", "#ffffff"),
        "primary_container": colors.get("primary_container", "#0d47a1"),
        "on_primary_container": colors.get("on_primary_container", "#ffffff"),
        "secondary": colors.get("secondary", "#8ab4f8"),
        "secondary_container": colors.get("secondary_container", colors.get("surface_container_high", "#292b2f")),
        "on_secondary_container": colors.get("on_secondary_container", colors.get("on_surface", "#e3e8ef")),
        "tertiary": colors.get("tertiary", "#efb8c8"),
        "tertiary_container": colors.get("tertiary_container", colors.get("surface_container_high", "#292b2f")),
        "on_tertiary_container": colors.get("on_tertiary_container", colors.get("on_surface", "#e3e8ef")),
        "error": colors.get("error", "#F2B8B5"),
        "on_error": colors.get("on_error", "#601410"),
        "error_container": colors.get("error_container", "#8C1D18"),
        "on_error_container": colors.get("on_error_container", "#F9DEDC"),
        "outline": colors.get("outline", "#8e918f"),
        "outline_variant": colors.get("outline_variant", colors.get("surface_variant", "#44464f")),
    }


def generate_css(colors):
    template = _load_template()
    for key, val in colors.items():
        template = template.replace("{" + key + "}", val)
    return template


def _load_template():
    return """/**
 * @name DMS
 * @description Material Design 3 recolor generated by DankMaterialShell.
 * @author DankMaterialShell
 * @version 1.0.0
 * @website https://github.com/AvengeMedia/DankMaterialShell
*/

.theme-dark,
.theme-light,
.visual-refresh.theme-dark,
.visual-refresh.theme-light,
.visual-refresh .theme-dark,
.visual-refresh .theme-light {
    --background-base-low: {surface} !important;
    --chat-background: {surface} !important;
    --chat-background-default: {surface} !important;
    --background-primary: {surface} !important;
    --bg-base-primary: {surface} !important;
    --home-background: {surface} !important;

    --background-base-lower: {surface_container_low} !important;
    --background-secondary: {surface_container_low} !important;
    --bg-base-secondary: {surface_container_low} !important;
    --custom-channel-members-bg: {surface_container_low} !important;

    --background-base-lowest: {surface_container} !important;
    --app-frame-background: {surface_container} !important;
    --background-tertiary: {surface_container} !important;
    --background-secondary-alt: {surface_container} !important;
    --bg-base-tertiary: {surface_container} !important;
    --__header-bar-background: {surface_container} !important;

    --background-surface-high: {surface_container_high} !important;
    --bg-surface-raised: {surface_container_high} !important;
    --card-primary-bg: {surface_container_high} !important;
    --activity-card-background: {surface_container_high} !important;

    --background-surface-higher: {surface_container_high} !important;
    --bg-surface-overlay: {surface_container_high} !important;
    --background-floating: {surface_container_high} !important;
    --background-nested-floating: {surface_container_high} !important;
    --autocomplete-bg: {surface_container_high} !important;

    --background-surface-highest: {surface_container_highest} !important;
    --modal-background: {surface_container_highest} !important;
    --modal-footer-background: {surface_container_highest} !important;
    --background-accent: {surface_container_highest} !important;
    --card-secondary-bg: {surface_container_highest} !important;
    --user-profile-overlay-background: {surface_container_highest} !important;

    --chat-border: color-mix(in srgb, {outline_variant} 50%, transparent) !important;

    --text-default: {on_surface} !important;
    --text-normal: {on_surface} !important;
    --text-primary: {on_surface} !important;
    --text-strong: {on_surface} !important;
    --header-primary: {on_surface} !important;
    --embed-title: {on_surface} !important;
    --interactive-active: {on_surface} !important;
    --input-text-default: {on_surface} !important;

    --text-secondary: {on_surface_variant} !important;
    --text-muted: {on_surface_variant} !important;
    --text-subtle: {on_surface_variant} !important;
    --text-tertiary: {on_surface_variant} !important;
    --chat-text-muted: {on_surface_variant} !important;
    --header-secondary: {on_surface_variant} !important;
    --header-muted: {on_surface_variant} !important;
    --text-muted-on-default: {on_surface_variant} !important;
    --text-low-contrast: {on_surface_variant} !important;

    --interactive-normal: {on_surface_variant} !important;
    --channels-default: {outline} !important;
    --channel-icon: {outline} !important;
    --icon-primary: {on_surface_variant} !important;
    --icon-secondary: {on_surface_variant} !important;
    --icon-tertiary: {on_surface_variant} !important;
    --interactive-icon-default: {on_surface_variant} !important;
    --interactive-hover: {on_surface} !important;
    --interactive-icon-hover: {on_surface} !important;
    --interactive-icon-active: {on_surface} !important;
    --interactive-text-hover: {on_surface} !important;
    --interactive-text-active: {on_surface} !important;

    --interactive-muted: {outline_variant} !important;
    --icon-muted: {outline} !important;
    --channel-text-area-placeholder: {outline} !important;
    --input-placeholder-text-default: {outline} !important;

    --text-link: {primary} !important;
    --text-brand: {primary} !important;
    --control-brand-foreground: {primary} !important;
    --control-brand-foreground-new: {primary} !important;
    --badge-text-brand: {primary} !important;

    --text-danger: {error} !important;
    --text-feedback-critical: {error} !important;
    --text-positive: #23a55a !important;
    --text-feedback-positive: #23a55a !important;
    --text-warning: #f0b232 !important;
    --text-feedback-warning: #f0b232 !important;
    --text-feedback-info: {secondary} !important;

    --background-modifier-hover: color-mix(in srgb, {on_surface} 8%, transparent) !important;
    --background-mod-subtle: color-mix(in srgb, {on_surface} 8%, transparent) !important;
    --bg-mod-faint: color-mix(in srgb, {on_surface} 8%, transparent) !important;
    --interactive-background-hover: color-mix(in srgb, {on_surface} 8%, transparent) !important;

    --background-modifier-active: color-mix(in srgb, {on_surface} 10%, transparent) !important;
    --background-mod-normal: color-mix(in srgb, {on_surface} 10%, transparent) !important;
    --interactive-background-active: color-mix(in srgb, {on_surface} 10%, transparent) !important;

    --background-modifier-selected: color-mix(in srgb, {primary} 14%, transparent) !important;
    --background-mod-strong: color-mix(in srgb, {primary} 14%, transparent) !important;
    --bg-mod-strong: color-mix(in srgb, {primary} 14%, transparent) !important;
    --interactive-background-selected: color-mix(in srgb, {primary} 14%, transparent) !important;

    --background-modifier-accent: color-mix(in srgb, {on_surface} 6%, transparent) !important;
    --background-message-hover: color-mix(in srgb, {on_surface} 4%, transparent) !important;
    --message-background-hover: color-mix(in srgb, {on_surface} 4%, transparent) !important;

    --background-message-highlight: color-mix(in srgb, {tertiary} 10%, transparent) !important;
    --background-message-highlight-hover: color-mix(in srgb, {tertiary} 14%, transparent) !important;
    --message-highlight-background-default: color-mix(in srgb, {tertiary} 10%, transparent) !important;
    --message-highlight-background-hover: color-mix(in srgb, {tertiary} 14%, transparent) !important;

    --background-mentioned: color-mix(in srgb, {primary} 10%, transparent) !important;
    --background-mentioned-hover: color-mix(in srgb, {primary} 14%, transparent) !important;
    --message-mentioned-background-default: color-mix(in srgb, {primary} 10%, transparent) !important;
    --message-mentioned-background-hover: color-mix(in srgb, {primary} 14%, transparent) !important;
    --mention-background: color-mix(in srgb, {primary} 15%, transparent) !important;
    --mention-foreground: {primary} !important;

    --message-reacted-background-default: color-mix(in srgb, {primary} 15%, transparent) !important;
    --message-reacted-text-default: {on_surface} !important;

    --brand-100: color-mix(in srgb, {primary} 12%, #ffffff) !important;
    --brand-200: color-mix(in srgb, {primary} 25%, #ffffff) !important;
    --brand-260: color-mix(in srgb, {primary} 33%, #ffffff) !important;
    --brand-300: color-mix(in srgb, {primary} 40%, #ffffff) !important;
    --brand-360: color-mix(in srgb, {primary} 55%, #ffffff) !important;
    --brand-400: color-mix(in srgb, {primary} 70%, #ffffff) !important;
    --brand-500: {primary} !important;
    --brand-560: color-mix(in srgb, {primary} 90%, #000000) !important;
    --brand-600: color-mix(in srgb, {primary} 85%, #000000) !important;
    --brand-700: color-mix(in srgb, {primary} 70%, #000000) !important;
    --brand-800: color-mix(in srgb, {primary} 55%, #000000) !important;
    --brand-900: color-mix(in srgb, {primary} 40%, #000000) !important;
    --brand-experiment: {primary} !important;
    --brand-experiment-360: {primary} !important;
    --brand-experiment-500: {primary} !important;
    --blurple-50: {primary} !important;
    --blue-500: {primary} !important;

    --bg-brand: {primary} !important;
    --background-brand: {primary} !important;
    --control-primary-background-default: {primary} !important;
    --control-primary-background-hover: color-mix(in srgb, {primary} 92%, {on_primary}) !important;
    --control-primary-background-active: color-mix(in srgb, {primary} 85%, {on_primary}) !important;
    --control-primary-text-default: {on_primary} !important;
    --control-primary-text-hover: {on_primary} !important;
    --control-primary-text-active: {on_primary} !important;
    --control-primary-icon-default: {on_primary} !important;
    --control-primary-icon-hover: {on_primary} !important;
    --control-primary-icon-active: {on_primary} !important;
    --button-filled-brand-background: {primary} !important;
    --button-filled-brand-background-hover: color-mix(in srgb, {primary} 92%, {on_primary}) !important;
    --button-filled-brand-background-active: color-mix(in srgb, {primary} 85%, {on_primary}) !important;
    --button-filled-brand-text: {on_primary} !important;

    --control-secondary-background-default: {surface_container_high} !important;
    --control-secondary-background-hover: {surface_container_highest} !important;
    --control-secondary-background-active: color-mix(in srgb, {surface_container_highest} 90%, {on_surface}) !important;
    --control-secondary-text-default: {on_surface} !important;
    --button-secondary-background: {surface_container_high} !important;
    --button-secondary-background-hover: {surface_container_highest} !important;
    --button-secondary-background-active: color-mix(in srgb, {surface_container_highest} 90%, {on_surface}) !important;
    --button-secondary-text: {on_surface} !important;
    --redesign-button-secondary-text: {on_surface} !important;

    --button-danger-background: {error} !important;
    --button-danger-background-hover: color-mix(in srgb, {error} 92%, {on_error}) !important;
    --button-danger-background-active: color-mix(in srgb, {error} 85%, {on_error}) !important;
    --button-danger-text: {on_error} !important;
    --control-critical-primary-background-default: {error} !important;
    --button-outline-danger-text: {error} !important;
    --button-outline-danger-text-hover: {error} !important;
    --button-outline-danger-text-active: {error} !important;
    --button-outline-danger-border: {error} !important;
    --button-outline-danger-border-hover: {error} !important;
    --button-outline-danger-border-active: {error} !important;

    --button-positive-background: #23a55a !important;
    --button-positive-background-hover: color-mix(in srgb, #23a55a 90%, #ffffff) !important;

    --button-outline-primary-text: {on_surface} !important;
    --button-outline-primary-text-hover: {on_surface} !important;
    --button-outline-primary-text-active: {on_surface} !important;
    --button-outline-primary-background-hover: color-mix(in srgb, {on_surface} 8%, transparent) !important;
    --button-outline-primary-background-active: color-mix(in srgb, {on_surface} 10%, transparent) !important;
    --button-outline-brand-text: {primary} !important;
    --button-outline-brand-background-hover: color-mix(in srgb, {primary} 10%, transparent) !important;
    --button-transparent-text: {on_surface} !important;
    --button-transparent-background-hover: color-mix(in srgb, {on_surface} 8%, transparent) !important;
    --button-transparent-background-active: color-mix(in srgb, {on_surface} 10%, transparent) !important;

    --redesign-input-control-selected: {primary} !important;
    --focus-primary: {primary} !important;
    --__adaptive-focus-ring-color: {primary} !important;

    --status-online: #23a55a !important;
    --status-positive: #23a55a !important;
    --status-speaking: #23a55a !important;
    --text-status-online: #23a55a !important;
    --icon-status-online: #23a55a !important;
    --status-idle: #f0b232 !important;
    --text-status-idle: #f0b232 !important;
    --icon-status-idle: #f0b232 !important;
    --status-dnd: #f13f43 !important;
    --text-status-dnd: #f13f43 !important;
    --icon-status-dnd: #f13f43 !important;
    --status-danger: #f13f43 !important;
    --status-offline: {outline} !important;
    --text-status-offline: {outline} !important;
    --icon-status-offline: {outline} !important;

    --background-feedback-critical: {error_container} !important;
    --notice-background-critical: {error_container} !important;
    --notice-text-critical: {on_error_container} !important;
    --icon-feedback-critical: {error} !important;
    --background-feedback-positive: {primary_container} !important;
    --notice-background-positive: {primary_container} !important;
    --notice-text-positive: {on_primary_container} !important;
    --background-feedback-info: {secondary_container} !important;
    --notice-background-info: {secondary_container} !important;
    --notice-text-info: {on_secondary_container} !important;
    --background-feedback-warning: {tertiary_container} !important;
    --notice-background-warning: {tertiary_container} !important;
    --notice-text-warning: {on_tertiary_container} !important;
    --badge-notification-background: {primary} !important;
    --background-feedback-notification: {primary} !important;
    --red-400: {error} !important;
    --red-430: {error} !important;
    --red-500: {error} !important;

    --input-background-default: {surface_container_highest} !important;
    --input-background: {surface_container_highest} !important;
    --channeltextarea-background: {surface_container_highest} !important;
    --deprecated-text-input-bg: {surface_container_highest} !important;
    --input-border-default: {outline_variant} !important;
    --input-border: {outline_variant} !important;
    --deprecated-text-input-border: {outline_variant} !important;
    --background-code: {surface_container} !important;
    --spoiler-hidden-background: {surface_container_highest} !important;
    --spoiler-revealed-background: {surface_container} !important;

    --scrollbar-auto-thumb: {outline_variant} !important;
    --scrollbar-thin-thumb: {outline_variant} !important;
    --scrollbar-auto-scrollbar-color-thumb: {outline_variant} !important;
    --scrollbar-auto-track: transparent !important;
    --scrollbar-thin-track: transparent !important;
    --scrollbar-auto-scrollbar-color-track: transparent !important;

    --border-faint: color-mix(in srgb, {outline_variant} 30%, transparent) !important;
    --border-subtle: color-mix(in srgb, {outline_variant} 50%, transparent) !important;
    --border-muted: {outline_variant} !important;
    --border-normal: {outline_variant} !important;
    --border-strong: {outline} !important;
}

::selection {
    background: color-mix(in srgb, {primary} 35%, transparent);
}

.theme-dark .highlight,
.theme-light .highlight {
    background: color-mix(in srgb, {primary} 30%, transparent);
    color: inherit;
}

.theme-dark span[class*="unreadPill"],
.theme-light span[class*="unreadPill"] {
    --interactive-text-active: {primary} !important;
}

.theme-dark div[class*="numberBadge"],
.theme-light div[class*="numberBadge"],
.theme-dark div[class*="newBadge"],
.theme-light div[class*="newBadge"],
.theme-dark div[class*="divider"] [class*="endCap"],
.theme-light div[class*="divider"] [class*="endCap"],
.theme-dark span[class*="botTag"],
.theme-light span[class*="botTag"],
.theme-dark div[class*="newMessagesBar"],
.theme-light div[class*="newMessagesBar"],
.theme-dark [class*="selectorButtonSelected"],
.theme-light [class*="selectorButtonSelected"],
.theme-dark div[class*="newTopicsBar"],
.theme-light div[class*="newTopicsBar"],
.theme-dark [class*="tooltipBrand"],
.theme-light [class*="tooltipBrand"],
.theme-dark [class*="roleCheckmark"],
.theme-light [class*="roleCheckmark"],
.theme-dark [class*="circleIconButton"],
.theme-light [class*="circleIconButton"],
.theme-dark [class*="modeButtonActive"],
.theme-light [class*="modeButtonActive"],
.theme-dark [class*="childWrapper"],
.theme-light [class*="childWrapper"] {
    --white: {on_primary} !important;
    --white-500: {on_primary} !important;
}

.theme-dark [class*="pageControl"] [class*="activeButton"],
.theme-light [class*="pageControl"] [class*="activeButton"] {
    color: {on_primary} !important;
    --white: {on_primary} !important;
    --white-500: {on_primary} !important;
}
"""


def main():
    parser = argparse.ArgumentParser(description="Generate Vesktop theme from DMS colors")
    parser.add_argument("-m", "--mode", choices=["dark", "light"], default="dark",
                        help="Color mode (default: dark)")
    parser.add_argument("-o", "--output",
                        help="Output path (default: auto-detect flatpak or native)")
    parser.add_argument("--stdout", action="store_true", help="Print CSS to stdout")
    args = parser.parse_args()

    if not os.path.exists(DMS_COLORS_PATH):
        print(f"Error: {DMS_COLORS_PATH} not found.", file=sys.stderr)
        sys.exit(1)

    dms_data = read_dms_colors(DMS_COLORS_PATH)
    colors = extract_colors(dms_data, args.mode)
    css = generate_css(colors)

    if args.stdout:
        print(css)
        return

    output = args.output
    if not output:
        flatpak_dir = os.path.dirname(FLATPAK_PATH)
        if os.path.exists(flatpak_dir):
            output = FLATPAK_PATH
        else:
            output = NATIVE_PATH

    os.makedirs(os.path.dirname(os.path.abspath(output)), exist_ok=True)
    with open(output, "w") as f:
        f.write(css)
    print(f"Written: {output}")
    print(f"Enable it in Vesktop: Settings → Themes → open Themes folder → place file there")
    print(f"  or for Vencord: cp '{output}' '{VENOCRD_PATH}'")


if __name__ == "__main__":
    main()
